
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      # Persist models between restarts - this is the key!
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 3s
      retries: 10

  ui:
    build: ./ui
    ports:
      - "3000:80"
    depends_on:
      - ollama
    environment:
      - VITE_OLLAMA_URL=/ollama

volumes:
  ollama-data:
    driver: local
